### ISSUE TITLE
Font - Enhancement

### ISSUE THREAD

**Issue by michalwa** [michalwa/GameFramework#9]
During the process of loading the image files for different characters, let the file names be specified in a JSON file located inside the font's folder.

**Comment by michalwa2003** [comment]
Consider removing the Font utility or making it obsolete, as it is inefficient and not sufficiently flexible!

**Comment by michalwa2003** [comment]
Suggested JSON config file format:
`[
  {"char" : "a", "filename" : "a_lower.png"},
  {"char" : "E", "filename" : "e_upper.png"}
]`

**Comment by michalwa2003** [comment]
JSON config file format update (add character width to remove unneccessary spacing):
`[{"char" : "a", "file" : "a_lower.png", "width" : 16}, {"char" : "!", "file" : "exclam.png", "width" : 3}]`

**Comment by michalwa2003** [comment]
Think about spritesheets.

**Comment by michalwa** [comment]
Meh...
